#!/usr/bin/env bash

if [ -z "$NVM_DIR" ]
then
    NVM_DIR="$HOME/.nvm"
fi

. $NVM_DIR/nvm.sh
nvm install
nvm use

set -e

pyvenv env
env/bin/pip install -r requirements.txt --upgrade


npm install
npm run build $@
