#!/usr/bin/env bash

if [ -z "$NVM_DIR" ]
then
    NVM_DIR="$HOME/.nvm"
fi

. $NVM_DIR/nvm.sh
nvm install
nvm use

set -e

pyvenv-3.4 env
env/bin/pip install -r requirements.txt --upgrade

scripts/get-private-data.sh

npm install
npm run build $@

env/bin/python manage.py collectstatic --noinput

if [[ $BUILD_PRODUCTION ]]
then
  echo ">> Running Migrations..."
  env/bin/python manage.py migrate
fi
