#!/usr/bin/env bash

set -e

pyvenv-3.4 env
env/bin/pip install -r requirements.txt --upgrade

scripts/get-private-data.sh

npm install
npm run build

env/bin/python manage.py collectstatic --noinput
