#!/usr/bin/env bash

set -e

export PATH=env/bin:${PATH}

./scripts/check-coverage.py

flake8 project scripts --ignore=E128,E501,E401 --exclude="migrations,settings,*/wsgi.py"

coverage html
coverage report

echo "All Python tests passed!"

npm test
