# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20161216_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionindexpage',
            name='post_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simplecontentpage',
            name='post_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
