# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 16:13
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtaildocs.blocks
import wagtail.wagtailimages.blocks
import wagtailmarkdown.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20161203_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('h1', wagtail.wagtailcore.blocks.CharBlock(classname='h1', icon='title', label='H1')), ('h2', wagtail.wagtailcore.blocks.CharBlock(classname='h2', icon='title', label='H2')), ('h3', wagtail.wagtailcore.blocks.CharBlock(classname='h3', icon='title', label='H3')), ('h4', wagtail.wagtailcore.blocks.CharBlock(classname='h4', icon='title', label='H4')), ('h5', wagtail.wagtailcore.blocks.CharBlock(classname='h5', icon='title', label='H5')), ('h6', wagtail.wagtailcore.blocks.CharBlock(classname='h6', icon='title', label='H6')), ('ansi', wagtail.wagtailcore.blocks.TextBlock(template='blocks/ansi.html')), ('document', wagtail.wagtaildocs.blocks.DocumentChooserBlock()), ('gist', wagtail.wagtailcore.blocks.CharBlock(icon='code', template='blocks/gist.html')), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('markdown', wagtailmarkdown.blocks.MarkdownBlock()), ('ol', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.CharBlock(label='List Item'), icon='list-ol', label='Ordered List', template='blocks/ordered-list.html')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('raw_html', wagtail.wagtailcore.blocks.RawHTMLBlock(label='Raw HTML')), ('secret', wagtail.wagtailcore.blocks.RichTextBlock(icon='password', template='blocks/secret.html')), ('ul', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.CharBlock(label='List Item'), icon='list-ul', label='Unordered List')))),
        ),
    ]
