author: Jake Howard
site_name: TheOrangeOne
url: https://theorangeone.net
timezone: Europe/London
language: en

pelican_plugins:
  - sitemap
  - filetime_from_git
  - pelican-jinja2content
  - metatags
  - autopages
  - screenfetch

sitemap_format: xml
