---

author: Jake Howard
site_name: TheOrangeOne
url: https://theorangeone.net
timezone: Europe/London
language: en

pelican_plugins:
  - sitemap
  - filetime_from_git
  - pelican-jinja2content
  - metatags
  - autopages
  - screenfetch
  - post_build
  - static_build

sitemap_format: xml


accounts:
  github:
    - GitHub
    - RealOrangeOne
    - https://github.com/{0}/
    - fa-github

  twitter:
    - Twitter
    - RealOrangeOne
    - https://twitter.com/{0}/
    - fa-twitter

  reddit:
    - Reddit
    - RealOrangeOne
    - https://reddit.com/u/{0}/
    - fa-reddit

  instagram:
    - Instagram
    - RealOrangeOne
    - https://instagram.com/{0}/
    - fa-instagram

  youtube:
    - YouTube
    - TheOrangeOneOfficial
    - https://youtube.com/users/{0}/
    - fa-youtube

  flickr:
    - Flickr
    - TheOrangeOne
    - https://flickr.com/photos/{0}/
    - fa-flickr

  bitbucket:
    - BitBucket
    - TheOrangeOne
    - https://bitbucket.com/{0}/
    - fa-bitbucket

  trello:
    - Trello
    - TheOrangeOne
    - https://trello.com/{0}/
    - fa-trello

  freenode:
    - Freenode IRC
    - TheOrangeOne
    - https://webchat.freenode.net/
    - fa-rss

  atomio:
    - AtomIO Slack
    - TheOrangeOne
    - https://atomio.slack.com/
    - fa-slack

  pcpartpicker:
    - PCPartPicker
    - TheOrangeOne97
    - https://uk.pcpartpicker.com/user/{0}/
    - fa-desktop

  codepen:
    - CodePen
    - TheOrangeOne
    - https://codepen.io/~{0}/
    - fa-codepen

  npm:
    - npm
    - TheOrangeOne
    - https://www.npmjs.com/~{0}/
    - fa-file-code-io

footer_accounts:
  - github
  - twitter
  - reddit
  - instagram
  - youtube
  - flickr

piwik:
  url: piwik.theorangeone.net
  site_id: 1
