# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_homepage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='post_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
