# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 21:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0032_add_bulk_delete_page_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flickr', models.URLField(help_text='Flickr Profile URL')),
                ('freenode', models.CharField(help_text='Freenode Username', max_length=15)),
                ('github', models.URLField(help_text='GitHub Profile URL')),
                ('reddit', models.URLField(help_text='Reddit Profile URL')),
                ('twitter', models.CharField(help_text='Twitter Username', max_length=15)),
                ('youtube', models.URLField(help_text='Youtube Channel URL')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
